// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgv86MHgvgS1bNY95R3YkTz7eZXAOcIGE',
    appId: '1:549316876004:web:eab0fc785bc58f8a5d3ef1',
    messagingSenderId: '549316876004',
    projectId: 'whatsapp-messanger-e7103',
    authDomain: 'whatsapp-messanger-e7103.firebaseapp.com',
    storageBucket: 'whatsapp-messanger-e7103.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEFY7BlRIoN_g-kNAPkq3wpxUlbzj87Zg',
    appId: '1:549316876004:android:1eb5c91dec711fc15d3ef1',
    messagingSenderId: '549316876004',
    projectId: 'whatsapp-messanger-e7103',
    storageBucket: 'whatsapp-messanger-e7103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_mC813mLdq82_iGFM7r2PMoyaVD7f8YY',
    appId: '1:549316876004:ios:2813e172fc9aeef65d3ef1',
    messagingSenderId: '549316876004',
    projectId: 'whatsapp-messanger-e7103',
    storageBucket: 'whatsapp-messanger-e7103.appspot.com',
    iosClientId: '549316876004-dlcp1t0o556sumn76rosohpho7nujl9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_mC813mLdq82_iGFM7r2PMoyaVD7f8YY',
    appId: '1:549316876004:ios:2813e172fc9aeef65d3ef1',
    messagingSenderId: '549316876004',
    projectId: 'whatsapp-messanger-e7103',
    storageBucket: 'whatsapp-messanger-e7103.appspot.com',
    iosClientId: '549316876004-dlcp1t0o556sumn76rosohpho7nujl9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
